version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/nodejs-app
    overwrite: yes  # Optional but useful during repeated deployments

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh  # Optional: to stop/delete old code
      timeout: 180
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: ec2-user
