version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Use your Node.js version
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running lint or tests if needed...

  build:
    commands:
      - echo Build started on `date`
      - node server.js

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no
